name: Deploy Frontend to Server

on:
  push:
    branches:
      - main  # Chạy khi có code mới trên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: fe-tixclick
      
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t myapp:latest -f ./Dockerfile .

      - name: Stop and Remove Existing Container if Any
        run: |
          CNAME=${{ env.CONTAINER_NAME }}

          # Check if the container exists
          if [ "$(docker ps -aq -f name=$CNAME)" ]; then
              if [ "$(docker ps -aq -f status=exited -f name=$CNAME)" ]; then
                  echo ":: Container $CNAME exists and is exited"
                  echo ":: Removing exited container - $CNAME"
                  docker rm $CNAME
              else
                  echo ":: Container $CNAME exists and is running"
                  echo ":: Stopping and removing running container - $CNAME"
                  docker stop $CNAME
                  docker rm $CNAME
              fi
          else
              echo ":: No existing container named $CNAME"
          fi

      - name: Run New Docker Container
        run: |
          CNAME=${{ env.CONTAINER_NAME }}
          echo ":: Running new container - $CNAME"
          docker run -d -p 5173:5173 --name $CNAME myapp:latest
